### ISSUE TITLE
Dashboard for App

### ISSUE THREAD

**Issue by tsi99** [chriswolfram/CollegeApp#10]
Dashboard for the "Explore Stanford" app that will allow admins to see analytics from the app. They can also see from where people are downloading the app and if they are touring in-person, where they are in real-time. Admins can also see a traffic heat map of visitors.

**Comment by nxmq** [comment]
How are collecting analytics atm? also this requires a web backend of some kind to serve the dashboard. maybe a subdomain on our site that points at an AWS instance running a webapp?

**Comment by tsi99** [comment]
I’m thinking that we should use/integrate Google Firebase or / and (if you can use more than one) Twitter Fabric.

Both of these seem to have good analytics and other free stuff. For example, (from what I understand) you can send free notifications through Firebase (something AWS charges for) and they have a great deep linking system.

Fabric allows users to sign into the app through just a phone number (they also authenticate users for free with that text message system). This is through a program called Digits. Signing in might be something we would look into later on so that users can unlock additional features. We would provide this user data from registration to the colleges.

Also, for the web portal, we would have these analytics, plus the ability for admins to customize the apps. Like change the names of the tour stops or change their descriptions, images, etc

**Comment by tsi99** [comment]
Update: I think Chris is just gonna do all of the analytics and make a Dashboard with Adobe Muse

**Comment by nxmq** [comment]
Im personally for Fabric. Also I think investing time in a server-side app that we can source data from would be useful. That would let admins set up a custom news feed/directory/map.

**Comment by chriswolfram** [comment]
For the server side stuff I'm going to use https://datadrop.wolframcloud.com because it's basically free and because I can more easily do more real analytics with it.

For the front end I'm either going to make something with Adobe Muse and figure out to host it later, or make it as a subdomain to Kincola.com and just use iframe type things to embed all of the charts, interactivity etc.
