### ISSUE TITLE
Tour Module

### ISSUE THREAD

**Issue by nxmq** [chriswolfram/CollegeApp#4]
This "issue" is for laying out the future of the Tour module, and tracking progress.

**Comment by chriswolfram** [comment]
1. Additional media types (video, audio, etc).
2. Server side landmark specification.
3. Customizable tours.
4. Shortest path for customizable tours.

**Comment by tsi99** [comment]
1. Flyover feature for each stop on the tour. (Since UC San Diego - they just want our Tours feature - has 3D Apple Maps already)

**Comment by tsi99** [comment]
1. Chat for tours (at the beginning of the tours app and at the bottom of info cards)
2. Add photo spheres capability

**Comment by tsi99** [comment]
Add compass I demoed with field of view

**Comment by tsi99** [comment]
Add estimated time for the tour a person selects based on average walking speed. That way they can make an informed decision of whether or not they have the time to complete the tour. This is useful especially since lots of people who visit campuses not on official visits don't have all day...

**Comment by tsi99** [comment]
I downloaded the latest version. Here are some enhancements (we have to present to UCSD soon):
- Make the current tour stop bubble a different color from the rest of the tour lines. (eg both are red right now - make the current stop bubble blue and the rest of the tour line red) 
- Also, make the current tour stop bubble size adjustable. When I zoom in, it just gets bigger and bigger. It should always remain the same size.
- We need to add the ability for people to see what a tour stop is before selecting it
- We need an extra screen right after selecting the tours where it shows you the map and gives you the option to delete stops that seem to far away
- For some reason, I can't see all the new media stuff (audio, video, Fyuses, etc) But I have the latest version...
- Add the tour progress bar right above card so it is more noticeable.
